AllCops:
  TargetRubyVersion: 2.3

Metrics/LineLength:
  Max: 120

Style/Documentation:
  Enabled: false

Metrics/CyclomaticComplexity:
  Max: 8

Style/ExpandPathArguments:
  Enabled: false

Gemspec/RequiredRubyVersion:
  Enabled: false

Layout/EndOfLine:
  EnforcedStyle: lf
