AllCops:
  TargetRubyVersion: 2.3

Style/Documentation:
  Enabled: false

Metrics/LineLength:
  Max: 100

Style/ExpandPathArguments:
  Enabled: false

Style/PercentLiteralDelimiters:
  PreferredDelimiters:
    '%w': '[]'

Style/Encoding:
  Enabled: false

Style/SymbolArray:
  Enabled: false

Layout/EndOfLine:
  Enabled: false
